apiVersion: apps/v1
kind: Deployment
metadata:
  name: loja-deployment
spec:
  selector:
    matchLabels:
      name: loja-pod
  template:
    metadata:
      labels:
        name: loja-pod
    spec:
      containers:
        - name: loja-container
          image: rafanercessian/aplicacao-loja:v1
          ports:
            - containerPort: 80
